# Generated by Django 5.2.5 on 2025-08-31 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datepublic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
